// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "achievement_badges": "شارات الإنجاز",
  "add_food_photo": "إضافة صورة الطعام",
  "artisan_bread": "خبز حرفي",
  "assorted_pastries_description": "معجنات وخبز وحلويات متنوعة من إنتاج اليوم",
  "available_food": "الطعام المتاح",
  "available_near_you": "متاح بالقرب منك",
  "bakery_owner_bio": "صاحب مخبز محلي شغوف بتقليل هدر الطعام",
  "beverages": "المشروبات",
  "bring_insulated_bags": "يرجى إحضار أكياس معزولة. العناصر تحتاج إلى تبريد",
  "browse_all": "تصفح الكل",
  "carbon_footprint_reduction": "تقليل البصمة الكربونية",
  "co_saved": "ثاني أكسيد الكربون المُوفر",
  "community_leaderboard": "لوحة المتصدرين",
  "contact_information": "معلومات الاتصال",
  "corner_bakery": "مخبز الركن",
  "current_location": "الموقع الحالي",
  "donations": "تبرعات",
  "donor": "متبرع",
  "environmental_impact": "التأثير البيئي",
  "eta": "الوقت المتوقع:",
  "expires_in_hours": "تنتهي صلاحيته خلال {hours} ساعات",
  "find_fresh_donations_near_you": "ابحث عن تبرعات طازجة بالقرب منك",
  "food_donor": "متبرع بالطعام",
  "food_rescued": "الطعام المُنقذ",
  "foodshare": "فود شير",
  "fresh_bakery_items": "مخبوزات طازجة",
  "fresh_sandwiches_pastries": "سندويتشات ومعجنات طازجة",
  "green_grocers": "البقالة الخضراء",
  "help_recipients_see_donation": "ساعد المستفيدين على رؤية ما تقدمه",
  "help_reduce_food_waste": "ساعد في تقليل هدر الطعام ودعم مجتمعك",
  "hours": "ساعات",
  "items": "عناصر",
  "items_available": "العناصر المتاحة",
  "join": "انضم",
  "kg": "كجم",
  "lbs": "رطل",
  "loaves": "أرغفة",
  "member_since": "عضو منذ",
  "miles": "أميال",
  "monthly_goals": "الأهداف الشهرية",
  "my_accepted_orders": "طلباتي المقبولة",
  "notifications": "الإشعارات",
  "order_details": "تفاصيل الطلب",
  "orders": "طلبات",
  "pending": "قيد الانتظار",
  "pickup_time": "وقت الاستلام",
  "pm": "مساءً",
  "post_food_donation": "نشر تبرع بالطعام",
  "profile": "الملف الشخصي",
  "quantity": "الكمية",
  "ready_for_pickup": "جاهز للاستلام",
  "ready_to_make_difference": "هل أنت مستعد لإحداث فرق اليوم؟",
  "recent_donations": "التبرعات الأخيرة",
  "recipient": "مستفيد",
  "rescue_food_tagline": "أنقذ الطعام، أطعم المجتمعات، قلل الهدر",
  "schedule": "الجدول الزمني",
  "see_your_impact": "شاهد الفرق الذي تحدثه",
  "servings": "حصص",
  "share_surplus_food": "شارك فائض طعامك",
  "sign_in_message": "سجل الدخول لمواصلة مساعدة مجتمعك",
  "special_instructions": "تعليمات خاصة",
  "sunshine_bakery": "مخبز الشمس المشرقة",
  "take_photo": "التقاط صورة",
  "to": "إلى:",
  "track_all": "تتبع الكل",
  "upload_from_gallery": "رفع من المعرض",
  "verified": "موثّق",
  "volunteer": "متطوع",
  "welcome_back": "مرحباً بعودتك!",
  "your_impact": "تأثيرك",
  "your_impact_this_month": "تأثيرك هذا الشهر"
};
static const Map<String,dynamic> _en = {
  "achievement_badges": "Achievement Badges",
  "add_food_photo": "Add Food Photo",
  "artisan_bread": "Artisan Bread",
  "assorted_pastries_description": "Assorted pastries, bread, and desserts from today's batch",
  "available_food": "Available Food",
  "available_near_you": "Available Near You",
  "bakery_owner_bio": "Local bakery owner passionate about reducing food waste",
  "beverages": "Beverages",
  "bring_insulated_bags": "Please bring insulated bags. Items need to be refrigerated",
  "browse_all": "Browse All",
  "carbon_footprint_reduction": "Carbon Footprint Reduction",
  "co_saved": "CO₂ Saved",
  "community_leaderboard": "Community Leaderboard",
  "contact_information": "Contact Information",
  "corner_bakery": "Corner Bakery",
  "current_location": "Current Location",
  "donations": "Donations",
  "donor": "Donor",
  "environmental_impact": "Environmental Impact",
  "eta": "ETA:",
  "expires_in_hours": "Expires in {hours} hours",
  "find_fresh_donations_near_you": "Find fresh donations near you",
  "food_donor": "Food Donor",
  "food_rescued": "Food Rescued",
  "foodshare": "FoodShare",
  "fresh_bakery_items": "Fresh Bakery Items",
  "fresh_sandwiches_pastries": "Fresh Sandwiches & Pastries",
  "green_grocers": "Green Grocers",
  "help_recipients_see_donation": "Help recipients see what you're offering",
  "help_reduce_food_waste": "Help reduce food waste and support your community",
  "hours": "Hours",
  "items": "Items",
  "items_available": "Items Available",
  "join": "Join",
  "kg": "Kg",
  "lbs": "Lbs",
  "loaves": "Loaves",
  "member_since": "Member since",
  "miles": "Miles",
  "monthly_goals": "Monthly Goals",
  "my_accepted_orders": "My Accepted Orders",
  "notifications": "Notifications",
  "order_details": "Order Details",
  "orders": "Orders",
  "pending": "Pending",
  "pickup_time": "Pickup Time",
  "pm": "PM",
  "post_food_donation": "Post Food Donation",
  "profile": "Profile",
  "quantity": "Quantity",
  "ready_for_pickup": "Ready for pickup",
  "ready_to_make_difference": "Ready to make a difference today?",
  "recent_donations": "Recent Donations",
  "recipient": "Recipient",
  "rescue_food_tagline": "Rescue Food, Feed Communities, Reduce Waste",
  "schedule": "Schedule",
  "see_your_impact": "See the difference you're making",
  "servings": "Servings",
  "share_surplus_food": "Share your surplus food",
  "sign_in_message": "Sign in to continue helping your community",
  "special_instructions": "Special Instructions",
  "sunshine_bakery": "Sunshine Bakery",
  "take_photo": "Take Photo",
  "to": "To:",
  "track_all": "Track All",
  "upload_from_gallery": "Upload from Gallery",
  "verified": "Verified",
  "volunteer": "Volunteer",
  "welcome_back": "Welcome Back!",
  "your_impact": "Your Impact",
  "your_impact_this_month": "Your Impact This Month"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
