// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "achievement_badges": "شارات الإنجاز",
  "add_food_photo": "إضافة صورة الطعام",
  "artisan_bread": "خبز حرفي",
  "assorted_pastries_description": "معجنات وخبز وحلويات متنوعة من إنتاج اليوم",
  "available_food": "الطعام المتاح",
  "available_near_you": "متاح بالقرب منك",
  "bakery_owner_bio": "صاحب مخبز محلي شغوف بتقليل هدر الطعام",
  "beverages": "المشروبات",
  "bring_insulated_bags": "يرجى إحضار أكياس معزولة. العناصر تحتاج إلى تبريد",
  "browse_all": "تصفح الكل",
  "carbon_footprint_reduction": "تقليل البصمة الكربونية",
  "co_saved": "ثاني أكسيد الكربون المُوفر",
  "community_leaderboard": "لوحة المتصدرين",
  "contact_information": "معلومات الاتصال",
  "corner_bakery": "مخبز الركن",
  "current_location": "الموقع الحالي",
  "donations": "تبرعات",
  "donor": "متبرع",
  "environmental_impact": "التأثير البيئي",
  "eta": "الوقت المتوقع:",
  "expires_in_hours": "تنتهي صلاحيته خلال ساعات",
  "expires_soon": "ينتهي قريباً",
  "find_fresh_donations_near_you": "ابحث عن تبرعات طازجة بالقرب منك",
  "food_donor": "متبرع بالطعام",
  "food_rescued": "الطعام المُنقذ",
  "foodshare": "فود شير",
  "fresh_bakery_items": "مخبوزات طازجة",
  "fresh_sandwiches_pastries": "سندويتشات ومعجنات طازجة",
  "green_grocers": "البقالة الخضراء",
  "help_recipients_see_donation": "ساعد المستفيدين على رؤية ما تقدمه",
  "help_reduce_food_waste": "ساعد في تقليل هدر الطعام ودعم مجتمعك",
  "hours": "ساعات",
  "items": "عناصر",
  "items_available": "العناصر المتاحة",
  "join": "انضم",
  "kg": "كجم",
  "lbs": "رطل",
  "loaves": "أرغفة",
  "member_since": "عضو منذ",
  "miles": "أميال",
  "monthly_goals": "الأهداف الشهرية",
  "my_accepted_orders": "طلباتي المقبولة",
  "notifications": "الإشعارات",
  "order_details": "تفاصيل الطلب",
  "orders": "طلبات",
  "pending": "قيد الانتظار",
  "pickup_time": "وقت الاستلام",
  "pm": "مساءً",
  "post_food_donation": "نشر تبرع بالطعام",
  "edit_food_donation": "تعديل تبرع بالطعام",
  "profile": "الملف الشخصي",
  "quantity": "الكمية",
  "ready_for_pickup": "جاهز للاستلام",
  "ready_to_make_difference": "هل أنت مستعد لإحداث فرق اليوم؟",
  "recent_donations": "التبرعات الأخيرة",
  "recipient": "مستفيد",
  "rescue_food_tagline": "أنقذ الطعام، أطعم المجتمعات، قلل الهدر",
  "schedule": "الجدول الزمني",
  "see_your_impact": "شاهد الفرق الذي تحدثه",
  "servings": "حصص",
  "share_surplus_food": "شارك فائض طعامك",
  "sign_in_message": "سجل الدخول لمواصلة مساعدة مجتمعك",
  "special_instructions": "تعليمات خاصة",
  "sunshine_bakery": "مخبز الشمس المشرقة",
  "take_photo": "التقاط صورة",
  "to": "إلى:",
  "track_all": "تتبع الكل",
  "upload_from_gallery": "رفع من المعرض",
  "verified": "موثّق",
  "volunteer": "متطوع",
  "welcome_back": "مرحباً بعودتك!",
  "your_impact": "تأثيرك",
  "your_impact_this_month": "تأثيرك هذا الشهر",
  "Get_Started": "ابدأ الآن",
  "Reduce_Food_Waste": "قلل هدر الطعام",
  "Turn_surplus_food_into_community_meals": "حول فائض الطعام إلى وجبات مجتمعية",
  "Feed_Communities": "أطعم المجتمعات",
  "Connect_donors_with_those_in_need": "اربط المتبرعين بالمحتاجين",
  "Volunteer_Network": "شبكة المتطوعين",
  "Join_drivers_making_a_difference": "انضم للسائقين الذين يصنعون الفرق",
  "This_field_is_required": "هذا الحقل مطلوب",
  "Email_is_required": "البريد الإلكتروني مطلوب",
  "Invalid_email_format": "صيغة البريد الإلكتروني غير صحيحة",
  "Password_is_required": "كلمة المرور مطلوبة",
  "Password_must_be_at_least_8_characters_long": "يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل",
  "Password_must_contain_at_least_one_uppercase_letter": "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
  "Password_must_contain_at_least_one_number": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
  "Password_must_contain_at_least_one_special_character": "يجب أن تحتوي كلمة المرور على رمز خاص واحد على الأقل",
  "Confirm_Password_is_required": "تأكيد كلمة المرور مطلوب",
  "Passwords_do_not_match": "كلمات المرور غير متطابقة",
  "Password_must_contain_at_least_one_lowercase_letter": "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل",
  "sign_up": "تسجيل",
  "Dont_have_an_account": "ليس لديك حساب؟ ",
  "Already_have_an_account": "هل لديك حساب بالفعل؟ ",
  "Sign_in": "تسجيل الدخول",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Enter_your_email": "أدخل البريد الإلكتروني الخاص بك",
  "Enter_your_password": "أدخل كلمة المرور الخاصة بك",
  "full_Name": "الاسم الكامل",
  "enter_your_full_name": "أدخل اسمك الكامل",
  "i_want_to": "أريد أن",
  "select_your_role": "اختر دورك",
  "please_select_a_role": "يرجى اختيار دور",
  "Resipient": "مستفيد",
  "Volunteer": "متطوع",
  "Donor": "متبرع",
  "Location": "الموقع",
  "City_State": "123 شارع، مدينة، محافظة",
  "Confirm_Password": "تأكيد كلمة المرور",
  "Confirm_your_password": "أكد كلمة المرور الخاصة بك",
  "Create_Account": "إنشاء حساب",
  "pls_confirm_terms_and_privacy": "يرجى الموافقة على الشروط والخصوصية",
  "Account_created_successfully": "تم إنشاء الحساب بنجاح",
  "i_agree_to_the": "أوافق على",
  "Terms_of_Service": "شروط الخدمة",
  "and": " و ",
  "Privacy_Policy": "سياسة الخصوصية",
  "Browse_Available_Orders": "تصفح الطلبات المتاحة",
  "Search_by_food_type_or_donor_name": "ابحث حسب نوع الطعام أو اسم المتبرع...",
  "All_Orders": "جميع الطلبات",
  "Urgent": "عاجل",
  "Nearby": "قريب",
  "Large": "كبير",
  "Donor_Information": "معلومات المتبرع",
  "Recipient_Information": "معلومات المستفيد",
  "My_Orders": "طلباتي",
  "Accepted": "مقبول",
  "Available": "متاح",
  "Reserved": "محجوز",
  "This_Week": "هذا الاسبوع",
  "all": "الكل",
  "near_me": "قريب مني",
  "Expires": "منتهي",
  "from": "من",
  "delivery": "توصيل",
  "Driver": "سائق",
  "days": "أيام",
  "pieces": "قطع",
  "Tomorrow": "غداً",
  "in_transit": "في النقل",
  "meals": "وجبات",
  "distance": "المسافة",
  "posted": "منشور",
  "hours_ago": "ساعات قبل",
  "delivery_window": "نافذه التسليم",
  "to_day": "اليوم",
  "Please_bring_insulated_bags_Items_need_to_be_refr": "يرجى إحضار حقائب معزولة. يجب حفظ المواد في",
  "home": "الرئيسية",
  "browse": "تصفح",
  "donate": "تبرع",
  "impact": "الاحصائيات",
  "category": "الفئة",
  "Select_food_category": "اختر فئة الطعام",
  "unit": "وحده",
  "change": "تغيير",
  "item_name": "اسم الصنف",
  "eg_Fresh_Vegetables_Baked_Goods": "مثال: خضروات طازجة، مخبوزات",
  "Description": "الوصف",
  "Additional_details_about_the_food": "تفاصيل إضافية عن الطعام...",
  "Available_for_Pickup": "متاح للاستلام",
  "Must_be_Picked_Up_By": "يجب استلامه قبل",
  "Pickup_Location": "موقع الاستلام",
  "data_confirmed": "تم تأكيد البيانات",
  "please_add_food_photo": "يرجى إضافة صورة الطعام",
  "data_not_confirmed": "لم يتم تأكيد البيانات",
  "timing": "توقيت",
  "total_donations": "إجمالي التبرعات",
  "Meals_Served": "الوجبات المقدمة",
  "This_Month": "هذا الشهر",
  "minutes_ago": "دقائق فائته",
  "expired": "منتهي",
  "portions": "حصص",
  "days_ago": "أيام فائته",
  "First_Donation": "أول تبرع",
  "Green_Hero": "البطل الأخضر",
  "Community_Champion": "بطل المجتمع",
  "Top_Donor": "أفضل متبرع",
  "Earned": "تم الحصول عليها",
  "Locked": "مقفلة",
  "Waste_Diverted": "النفايات المحولة",
  "Lives_Fed": "الأرواح المطعمة",
  "jan": "يناير",
  "feb": "فبراير",
  "mar": "مارس",
  "apr": "أبريل",
  "un_read": "غير مقروء",
  "Your_donation_of_fresh_vegetables_has_been_accepted": "تم قبول تبرعك من الخضروات الطازجة",
  "order_accepted": "تم قبول الطلب",
  "important": "مهم",
  "profile_editing": "تعديل الملف الشخصي",
  "settings": "الإعدادات",
  "about_us": "من نحن",
  "Tell_the_community_about_your_organization": "أخبر المجتمع عن منظمتك...",
  "Bio": "السيرة الذاتية",
  "account_settings": "إعدادات الحساب",
  "save": "حفظ",
  "change_password": "تغيير كلمة المرور",
  "Email_Preferences": "تفضيلات البريد الإلكتروني",
  "Delete_Account": "حذف الحساب",
  "Update_your_personal_information": "تحديث معلوماتك الشخصية",
  "account": "الحساب",
  "Language": "اللغة",
  "App_Preferences": "تفضيلات التطبيق",
  "Dark_Mode": "الوضع الداكن",
  "Switch_to_dark_theme": "التبديل إلى المظهر الداكن",
  "Switch_to_light_theme": "التبديل إلى المظهر الفاتح",
  "phone_number": "رقم الهاتف",
  "Organization_Name": "اسم المنظمة",
  "Basic_Information": "المعلومات الأساسية",
  "Business_Details": "تفاصيل العمل",
  "Website": "الموقع الإلكتروني",
  "Business_Hours": "ساعات العمل",
  "sign_out": "تسجيل الخروج",
  "Push_Notifications": "الإشعارات الفورية",
  "Get_notified_about_new_orders": "احصل على إشعارات حول الطلبات الجديدة",
  "SMS_Alerts": "تنبيهات الرسائل النصية",
  "Urgent_delivery_notifications": "إشعارات التوصيل العاجلة",
  "Email_Updates": "تحديثات البريد الإلكتروني",
  "Weekly_impact_reports": "تقارير التأثير الأسبوعية",
  "pounds_saved": "الأرطال المحفوظة",
  "Meals_Donated": "الوجبات المتبرع بها",
  "Organizations_Helped": "المنظمات المساعدة",
  "Enter_full_address_including_city_and_state": "أدخل العنوان الكامل بما في ذلك المدينة والمحافظة",
  "Enter_valid_address": "أدخل عنوانًا صالحًا",
  "cancle": "إلغاء",
  "Are_U_Sure_You_Want_To_Sign_Out": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "please_enter_your_phone_number": "يرجى إدخال رقم هاتفك",
  "Current_Password": "كلمة المرور الحالية",
  "New_Password": "كلمة المرور الجديدة",
  "Confirm_New_Password": "تأكيد كلمة المرور الجديدة",
  "Current_Password_is_required": "يجب أن تحتوي كلمة المرور الحالية",
  "Enter_Your_Current_Password": "أدخل كلمة المرور الحالية الخاصة بك",
  "Enter_Your_New_Password": "أدخل كلمة المرور الجديدة الخاصة بك",
  "Enter_Your_Confirm_Password": "أدخل تأكيد كلمة المرور الخاصة بك",
  "please_select_expiry_date": "يرجى اختيار تاريخ الانتهاء",
  "please_select_unit": "يرجى اختيار وحده",
  "please_select_category": "يرجى اختيار الفئة",
  "time_just_now": "منذ ثوانٍ",
  "time_minute_ago": "منذ دقيقة",
  "time_minutes_ago": "منذ {count} دقائق",
  "time_hour_ago": "منذ ساعة",
  "time_two_hours_ago": "منذ ساعتين",
  "time_hours_ago": "منذ {count} ساعات",
  "time_yesterday": "أمس",
  "Post_Deleted_Successfully": "تم حذف المنشور بنجاح",
  "Are_u_Sure_You_Want_To_Delete_this_post": "هل أنت متأكد أنك تريد حذف هذا المنشور؟",
  "Delete_Post": "حذف المنشور",
  "Delete": "حذف",
  "Something_went_wrong": "هناك خطأ ما يرجى المحاولة مرة أخرى في وقت لاحق",
  "Edit": "تعديل",
  "Are_u_Sure_You_Want_To_Delete_Account": "هل أنت متأكد أنك تريد حذف الحساب؟",
  "Account_Deleted_Successfully": "تم حذف الحساب بنجاح",
  "No_expiring_soon_posts_found": "لم يتم العثور على منشورات تنتهي قريبًا.",
  "No_Posts_found": "لم يتم العثور على منشورات.",
  "Kilogram": "كيلوجرام",
  "Pound": "رطل",
  "Pieces": "قطع",
  "Ton": "طن",
  "meat_left_overs": "بقايا اللحوم",
  "vegetables_left_overs": "بقايا الخضروات",
  "fruits_left_overs": "بقايا الفواكه",
  "other": "اخرى",
  "Other": "أخرى"
};
static const Map<String,dynamic> _en = {
  "achievement_badges": "Achievement Badges",
  "add_food_photo": "Add Food Photo",
  "artisan_bread": "Artisan Bread",
  "assorted_pastries_description": "Assorted pastries, bread, and desserts from today's batch",
  "available_food": "Available Food",
  "available_near_you": "Available Near You",
  "bakery_owner_bio": "Local bakery owner passionate about reducing food waste",
  "beverages": "Beverages",
  "bring_insulated_bags": "Please bring insulated bags. Items need to be refrigerated",
  "browse_all": "Browse All",
  "carbon_footprint_reduction": "Carbon Footprint Reduction",
  "co_saved": "CO₂ Saved",
  "community_leaderboard": "Community Leaderboard",
  "contact_information": "Contact Information",
  "corner_bakery": "Corner Bakery",
  "current_location": "Current Location",
  "donations": "Donations",
  "donor": "Donor",
  "environmental_impact": "Environmental Impact",
  "eta": "ETA:",
  "expires_in_hours": "Expires in hours",
  "expires_soon": "Expires soon",
  "find_fresh_donations_near_you": "Find fresh donations near you",
  "food_donor": "Food Donor",
  "food_rescued": "Food Rescued",
  "foodshare": "FoodShare",
  "fresh_bakery_items": "Fresh Bakery Items",
  "fresh_sandwiches_pastries": "Fresh Sandwiches & Pastries",
  "green_grocers": "Green Grocers",
  "help_recipients_see_donation": "Help recipients see what you're offering",
  "help_reduce_food_waste": "Help reduce food waste and support your community",
  "hours": "Hours",
  "items": "Items",
  "items_available": "Items Available",
  "join": "Join",
  "kg": "Kg",
  "lbs": "Lbs",
  "loaves": "Loaves",
  "member_since": "Member since",
  "miles": "Miles",
  "monthly_goals": "Monthly Goals",
  "my_accepted_orders": "My Accepted Orders",
  "notifications": "Notifications",
  "order_details": "Order Details",
  "orders": "Orders",
  "pending": "Pending",
  "pickup_time": "Pickup Time",
  "pm": "PM",
  "post_food_donation": "Post Food Donation",
  "edit_food_donation": "Edit Food Donation",
  "profile": "Profile",
  "quantity": "Quantity",
  "ready_for_pickup": "Ready for pickup",
  "ready_to_make_difference": "Ready to make a difference today?",
  "recent_donations": "Recent Donations",
  "recipient": "Recipient",
  "rescue_food_tagline": "Rescue Food, Feed Communities, Reduce Waste",
  "schedule": "Schedule",
  "see_your_impact": "See the difference you're making",
  "servings": "Servings",
  "share_surplus_food": "Share your surplus food",
  "sign_in_message": "Sign in to continue helping your community",
  "special_instructions": "Special Instructions",
  "sunshine_bakery": "Sunshine Bakery",
  "take_photo": "Take Photo",
  "to": "To:",
  "track_all": "Track All",
  "upload_from_gallery": "Upload from Gallery",
  "verified": "Verified",
  "volunteer": "Volunteer",
  "welcome_back": "Welcome Back!",
  "your_impact": "Your Impact",
  "your_impact_this_month": "Your Impact This Month",
  "Get_Started": "Get Started",
  "Reduce_Food_Waste": "Reduce Food Waste",
  "Turn_surplus_food_into_community_meals": "Turn surplus food into community meals",
  "Feed_Communities": "Feed Communities",
  "Connect_donors_with_those_in_need": "Connect donors with those in need",
  "Volunteer_Network": "Volunteer Network",
  "Join_drivers_making_a_difference": "Join drivers making a difference",
  "This_field_is_required": "This field is required",
  "Email_is_required": "Email is required",
  "Invalid_email_format": "Invalid email format",
  "Password_is_required": "Password is required",
  "Password_must_be_at_least_8_characters_long": "Password must be at least 8 characters long",
  "Password_must_contain_at_least_one_uppercase_letter": "Password must contain at least one uppercase letter",
  "Password_must_contain_at_least_one_number": "Password must contain at least one number",
  "Password_must_contain_at_least_one_special_character": "Password must contain at least one special character",
  "Confirm_Password_is_required": "Confirm Password is required",
  "Passwords_do_not_match": "Passwords do not match",
  "Password_must_contain_at_least_one_lowercase_letter": "Password must contain at least one lowercase letter",
  "sign_up": "sign up",
  "Dont_have_an_account": "Don’t have an account? ",
  "Already_have_an_account": "Already have an account? ",
  "Sign_in": "Sign in",
  "Email": "Email",
  "Password": "Password",
  "Enter_your_email": "Enter your email",
  "Enter_your_password": "Enter your password",
  "full_Name": "Full Name",
  "enter_your_full_name": "Enter your full name",
  "i_want_to": "I want to",
  "select_your_role": "Select your role",
  "please_select_a_role": "Please select a role",
  "Resipient": "Resipient",
  "Volunteer": "Volunteer",
  "Donor": "Donor",
  "Location": "Location",
  "City_State": "123 St, City, State",
  "Confirm_Password": "Confirm Password",
  "Confirm_your_password": "Confirm your password",
  "Create_Account": "Create Account",
  "pls_confirm_terms_and_privacy": "pls confirm terms and privacy",
  "Account_created_successfully": "Account created successfully",
  "i_agree_to_the": "I agree to the",
  "Terms_of_Service": "Terms of Service",
  "and": " and ",
  "Privacy_Policy": "Privacy Policy",
  "Browse_Available_Orders": "Browse Available Orders",
  "Search_by_food_type_or_donor_name": "Search by food type or donor name...",
  "All_Orders": "All Orders",
  "Urgent": "Urgent",
  "Nearby": "Nearby",
  "Large": "Large",
  "Donor_Information": "Donor Information",
  "Recipient_Information": "Recipient Information",
  "My_Orders": "My Orders",
  "Accepted": "Accepted",
  "Available": "Available",
  "Reserved": "Reserved",
  "This_Week": "This Week",
  "all": "All",
  "near_me": "Near Me",
  "Expires": "Expires",
  "from": "From",
  "delivery": "Delivery",
  "Driver": "Driver",
  "days": "days",
  "pieces": "pieces",
  "Tomorrow": "Tomorrow",
  "in_transit": "In Transit",
  "meals": "Meals",
  "distance": "Distance",
  "posted": "posted",
  "hours_ago": "hours_ago",
  "delivery_window": "Delivery Window",
  "to_day": "To Day",
  "Please_bring_insulated_bags_Items_need_to_be_refr": "Please bring insulated bags. Items need to be refr",
  "home": "Home",
  "browse": "Browse",
  "donate": "Donate",
  "impact": "Impact",
  "category": "Category",
  "Select_food_category": "Select food category",
  "unit": "Unit",
  "change": "Change",
  "item_name": "Item Name",
  "eg_Fresh_Vegetables_Baked_Goods": "e.g., Fresh Vegetables, Baked Goods",
  "Description": "Description",
  "Additional_details_about_the_food": "Additional details about the food...",
  "Available_for_Pickup": "Available for Pickup",
  "Must_be_Picked_Up_By": "Must be Picked Up By",
  "Pickup_Location": "Pickup Location",
  "data_confirmed": "data confirmed",
  "please_add_food_photo": "please add food photo",
  "data_not_confirmed": "data not confirmed",
  "timing": "Timing",
  "total_donations": "Total Donations",
  "Meals_Served": "Meals Served",
  "This_Month": "This Month",
  "minutes_ago": "Minutesa Ago",
  "expired": "expired",
  "portions": "portions",
  "days_ago": "Days Ago",
  "First_Donation": "First Donation",
  "Green_Hero": "Green Hero",
  "Community_Champion": "Community Champion",
  "Top_Donor": "Top Donor",
  "Earned": "Earned",
  "Locked": "Locked",
  "Waste_Diverted": "Waste Diverted",
  "Lives_Fed": "Lives Fed",
  "jan": "Jan",
  "feb": "Feb",
  "mar": "Mar",
  "apr": "Apr",
  "un_read": "Un Read",
  "Your_donation_of_fresh_vegetables_has_been_accepted": "Your donation of fresh vegetables has been accepted",
  "order_accepted": "Order Accepted",
  "important": "Important",
  "profile_editing": "Profile Editing",
  "settings": "Settings",
  "about_us": "About Us",
  "Tell_the_community_about_your_organization": "Tell the community about your organization...",
  "Bio": "Bio",
  "account_settings": "Account Settings",
  "save": "Save",
  "change_password": "Change Password",
  "Email_Preferences": "Email Preferences",
  "Delete_Account": "Delete Account",
  "Update_your_personal_information": "Update your personal information",
  "account": "Account",
  "Language": "Language",
  "App_Preferences": "App Preferences",
  "Dark_Mode": "Dark Mode",
  "Switch_to_dark_theme": "Switch to dark theme",
  "Switch_to_light_theme": "Switch to light theme",
  "phone_number": "Phone Number",
  "Organization_Name": "Organization Name",
  "Basic_Information": "Basic Information",
  "Business_Details": "Business Details",
  "Website": "Website",
  "Business_Hours": "Business Hours",
  "sign_out": "Sign Out",
  "Push_Notifications": "Push Notifications",
  "Get_notified_about_new_orders": "Get notified about new orders",
  "SMS_Alerts": "SMS Alerts",
  "Urgent_delivery_notifications": "Urgent delivery notifications",
  "Email_Updates": "Email Updates",
  "Weekly_impact_reports": "Weekly impact reports",
  "pounds_saved": "Pounds Saved",
  "Meals_Donated": "Meals Donated",
  "Organizations_Helped": "Organizations Helped",
  "Enter_full_address_including_city_and_state": " Enter full address including city and state",
  "Enter_valid_address": "Enter valid address",
  "cancle": "Cancel",
  "Are_U_Sure_You_Want_To_Sign_Out": "Are U Sure You Want To Sign Out?",
  "please_enter_your_phone_number": "Please enter your phone number",
  "Current_Password": "Current Password",
  "New_Password": "New Password",
  "Confirm_New_Password": "Confirm New Password",
  "Current_Password_is_required": "Current Password is required",
  "Enter_Your_Current_Password": "Enter Your Current Password",
  "Enter_Your_New_Password": "Enter Your New Password",
  "Enter_Your_Confirm_Password": "Enter Your Confirm Password",
  "please_select_expiry_date": "please select expiry date",
  "please_select_unit": "please select unit",
  "please_select_category": "please select category",
  "time_just_now": "Just now",
  "time_minute_ago": "A minute ago",
  "time_minutes_ago": "{count} minutes ago",
  "time_hour_ago": "An hour ago",
  "time_two_hours_ago": "Two hours ago",
  "time_hours_ago": "{count} hours ago",
  "time_yesterday": "Yesterday",
  "Post_Deleted_Successfully": "Post Deleted Successfully",
  "Are_u_Sure_You_Want_To_Delete_this_post": "Are u Sure You Want To Delete this post",
  "Delete_Post": "Delete Post",
  "Delete": "Delete",
  "Something_went_wrong": "Something went wrong please try again later",
  "Edit": "Edit",
  "Are_u_Sure_You_Want_To_Delete_Account": "Are u Sure You Want To Delete Account",
  "Account_Deleted_Successfully": "Account Deleted Successfully",
  "No_expiring_soon_posts_found": "No expiring soon posts found.",
  "No_Posts_found": "No Posts found.",
  "Kilogram": "Kilogram",
  "Pound": "Pound",
  "Pieces": "Pieces",
  "Ton": "Ton",
  "meat_left_overs": "Meat Left Overs",
  "vegetables_left_overs": "Vegetables Left Overs",
  "fruits_left_overs": "Fruits Left Overs",
  "other": "Other",
  "Other": "Other"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
